jakub_mylangs:
    resource: "@JakubMylangsBundle/Resources/config/routing.yml"
    #prefix:   /

#_acme_demo:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
