<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html"; charset=utf-8" />
        <title>{% block title %}Hello in Mylangs application{% endblock %}</title>
        {% block stylesheets %}
            <link href="{{ asset('/bundles/jakubmylangs/css/main.css') }}" type="text/css" rel="stylesheet" />
        {% endblock %}
        <link rel="shortcut icon" href="{{ asset('favicon.ico') }}" />
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script><script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    </head>
    <body>
        {% block content %}
            <div class="ctn ce">
                <h1>Welcome into MyLangs application by Jakub Luczynski</h1>
                <div id="en" class="en flag"></div>
                <div id="de" class="de flag"></div>
            </div>
            <div class="ctn ce">
                <p>Please login into your account</p>
                {% if error %}
                    <p>{{ error.message }}</p>
                {% endif %}
                {{ form(form, {'attr': {'novalidate': 'novalidate'}}) }}
            </div>
            <div class="ctn ce">
                <a href="{{ path('register') }}">registration</a>
            </div>
        {% endblock %}
        {% block javascripts %}
            <script src="{{ asset('/js/main.js') }}" type="text/javascript"></script>
        {% endblock %}
    </body>
</html>