Jakub\MylangsBundle\Entity\Login:
    getters:
        passwordLegal:
            - "True": { message: "Login and password can't be the same!" }
    properties:
        _sUserName:
            - NotBlank: {message: "Write your login"}
        _sPassword:
            - NotBlank: {message: "Write your password"}