Jakub\MylangsBundle\Entity\Login:
    getters:
        passwordLegal:
            - "True": { message: "Login and password can't be the same!" }
    properties:
        _sUserName:
            - NotBlank: {message: "Write your login"}
        _sPassword:
            - NotBlank: {message: "Write your password"}
            
Jakub\MylangsBundle\Entity\Register:
    getters:
        userDuplicated:
            - "False": { message: "The user already exists!"}
        emailDuplicated:
            - "False": { message: "The email address already exists!"}
        passwordLegal:
            - "True": { message: "Login and password can't be the same!" }
        passwordConfirm:
            - "True": { message: "Both passwords must be the same!" }
        #minPasswordLength:
        #    - "True": { message: "Password is too short!" }
        #minUsernameLength:
        #    - "True": { message: "Username is too short!" }

    properties:
        _sUserName:
            - NotBlank: {message: "Write your login"}
            - Length: {min: 3, minMessage: "Username is too short!"}
            - Email: {checkMX: true, checkHost: true}
        _sPassword:
            - NotBlank: {message: "Write your password"}
            - Length: {min: 4, minMessage: "Password is too short!"}
        _bTermsAccepted:
            - NotBlank: {message: "Confirm terms"}