Jakub\MylangsBundle\Entity\Login:
    getters:
        passwordLegal:
            - "True": { message: "Hasło i login nie mogą być takie same!" }
    properties:
        _sLogin:
            - NotBlank: {message: Wpisz login}
        _sPassword:
            - NotBlank: {message: Wpisz hasło}